feat: added rcs code snippets
Vonage/vonage-node-code-snippets pull request #157
Opened 2024-08-25 22:42 UTC by manchuck

## Description

## Motivation and Context

## Testing Details

## Example Output(if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] All new and existing tests passed.

2024-08-30 17:11 UTC, superchilled requested changes
Looks good overall, but a few fixes needed (which I've indicated in the comments). You also need to add `RCS_SENDER_ID` to `.env-example`

2024-08-30 17:11 UTC, superchilled commented on messages/rcs/send-rich-card-carousel.js
> +const RCS_SENDER_ID = process.env.RCS_SENDER_ID;
This snippet needs env vars for image url and video url

```suggestion
const RCS_SENDER_ID = process.env.RCS_SENDER_ID;
const IMAGE_URL = process.env.IMAGE_URL;
const VIDEO_URL = process.env.VIDEO_URL;
```

2024-08-30 17:11 UTC, superchilled commented on messages/rcs/send-rich-card-carousel.js
> +                    fileUrl: "'$IMAGE_URL'",
```suggestion
                    fileUrl: IMAGE_URL,
```

2024-08-30 17:11 UTC, superchilled commented on messages/rcs/send-rich-card-carousel.js
> +                    fileUrl: "'$VIDEO_URL'",
```suggestion
                    fileUrl: VIDEO_URL,
```

2024-08-30 17:11 UTC, superchilled commented on messages/rcs/send-rich-card-standalone.js
> +const RCS_SENDER_ID = process.env.RCS_SENDER_ID;
```suggestion
const RCS_SENDER_ID = process.env.RCS_SENDER_ID;
const IMAGE_URL = process.env.IMAGE_URL;
```

2024-08-30 17:11 UTC, superchilled commented on messages/rcs/send-rich-card-standalone.js
> +                  fileUrl: "'$IMAGE_URL'",
```suggestion
                  fileUrl: IMAGE_URL,
```

2024-08-30 17:11 UTC, superchilled commented on messages/rcs/send-suggested-action-open-url.js
> +      },
I think this might be a copy/paste error. It should be something like:

```suggestion
      contentMessage: {
        text: "Check out our latest offers!",
        suggestions: [
          {
            action: {
              text: "Open product page",
              postbackData: "postback_data_1234",
              openUrlAction: { 
                url: "http://example.com/", 
              },
            },
          },
        ],
      },
```

2024-08-30 17:11 UTC, superchilled commented on messages/rcs/send-text.js
> +    text: "Hello from Vonage Messages API",
```suggestion
    text: "This is an RCS text message sent via the Vonage Messages API",
```

2024-09-04 08:22 UTC, superchilled reviewed
Hey @manchuck not sure if you saw my comment [here](https://github.com/Vonage/vonage-node-code-snippets/pull/157#pullrequestreview-2273073644) about updating the `.env.example`

2024-09-05 13:47 UTC, manchuck commented
@superchilled, sorry, I needed to force push since I amended the commit.

2024-09-06 17:05 UTC, superchilled approved these changes
Thanks for making the amendments. Loooks good to go. 👍🏾

2024-09-09 10:32 UTC, merged