Tony building blocks
Vonage/vonage-node-code-snippets pull request #17
Opened 2018-06-04 10:46 UTC by tbedford

## Description

Some initial Node building blocks to kick things off. I am not a Node programmer so feel free to amend my code as required. I have tested the code and in most cases you just need to paste in CALL_UUID.

2018-06-08 11:43 UTC, mheap requested changes

2018-06-08 11:43 UTC, mheap commented on voice/download-a-recording.js
> +}, {debug: false});
We don't have to set `debug: false`

2018-06-08 11:43 UTC, mheap commented on voice/download-a-recording.js
> +  if(err) { console.error(err); }
It's common to return in an `err` block instead of using an `else` block:

```javascript
nexmo.files.save(RECORDING_URL, 'test.mp3', (err, res) => {
  if(err) { return console.error(err); }
  console.log(res);
});
```

2018-06-08 11:43 UTC, mheap commented on voice/earmuff-a-call.js
> +setTimeout(unearmuff, 5000); // delay 5 seconds
This should be 3 seconds, not 5

2018-06-08 11:43 UTC, mheap commented on voice/play-tts-into-call.js
> +nexmo.calls.talk.start(CALL_UUID, { text: TEXT, voiceName: 'Emma', loop: 1 }, (err, res) => {
This shouldn't loop

2018-06-08 11:43 UTC, mheap commented on voice/play-tts-into-call.js
> +function stop_talk (){
We don't need to stop the talk action as it shouldn't loop

2018-06-08 11:43 UTC, mheap commented on voice/download-a-recording.js
> +
Trim the files so that there's no empty trailing blank lines

2018-06-08 11:43 UTC, mheap commented on voice/stream-audio-into-call.js
> +nexmo.calls.stream.start(CALL_UUID, { stream_url: [AUDIO_URL], loop: 1 }, (err, res) => {
No looping

2018-06-14 12:36 UTC, AlexLakatos approved these changes
LGTM 🏗

2018-06-14 14:33 UTC, mheap approved these changes

2018-06-14 14:35 UTC, merged