Add some account-related code examples
Vonage/vonage-node-code-snippets pull request #52
Opened 2019-01-10 15:26 UTC by lornajane

We recently added specs for the account balance and configure account examples. I added the secret management ones as well while I was here.

2019-02-18 16:36 UTC, lukeocodes requested changes
a couple of things you might be able to do;

uniform condition on error across the building blocks. we have a nice callback `(err, result)` and only in some cases do we log the error if we receive one

destructing assignment on the consts from .env (or even, just use the .env variables directly instead of assigning them to a const)

one thing to change, a hardcoded secret needs removing by the looks of it :)

2019-02-18 16:36 UTC, lukeocodes commented on account/delete-secret.js
> +const SECRET_ID = "2e5751a6-8cae-4795-afda-5ef86320deef"
Should this be hardcoded?

2019-02-18 16:43 UTC, lukeocodes commented on account/account-balance.js
> +const NEXMO_API_KEY = process.env.NEXMO_API_KEY
```suggestion
const { NEXMO_API_KEY, NEXMO_API_SECRET } = process.env
```

2019-02-18 16:49 UTC, AlexLakatos commented on account/account-balance.js
> +    console.log(String(result.value.toFixed(2)) + " EUR");
```suggestion
    console.log(`${result.value.toFixed(2)} EUR`);
```

2019-02-18 16:51 UTC, AlexLakatos commented on account/delete-secret.js
> +const SECRET_ID = "2e5751a6-8cae-4795-afda-5ef86320deef"
I don't think it should

2019-02-19 14:28 UTC, lukeocodes commented on account/create-secret.js
> +const SECRET_ID = process.env.SECRET_ID
`const SECRET_ID = process.env.SECRET_ID` this constant isnt used. I guess, because you're using `const secret = 'awes0meNewSekret!!;';` below.

2019-03-05 10:23 UTC, lornajane commented on account/delete-secret.js
> +const SECRET_ID = "2e5751a6-8cae-4795-afda-5ef86320deef"
Definitely not! Good spot

2019-03-05 10:34 UTC, lornajane commented on account/account-balance.js
> +const NEXMO_API_KEY = process.env.NEXMO_API_KEY
This is more elegant but IMO less readable (especially for less experienced coders) so I'll leave it as-is

2019-03-05 10:35 UTC, lornajane commented on account/create-secret.js
> +const SECRET_ID = process.env.SECRET_ID
Ah yes, I don't need that bit of config in this example. Thanks :)

2019-03-11 14:44 UTC, lukeocodes approved these changes

2019-03-15 12:46 UTC, merged