Add Node Messages API snippets
Vonage/vonage-node-code-snippets pull request #87
Opened 2020-06-26 09:04 UTC by marklewin

Adding new Node snippets for Messages API. The specs [are here](https://github.com/Nexmo/code-snippet-specs/tree/master/olympus/messages).

**Facebook**

- [ ] Send an Image Message
- [ ] Send a Video Message
- [ ] Send an Audio Message
- [ ] Send a Message Template
- [ ] Send a File Message

**WhatsApp**
- [ ] Send a Message Template (MTM)
- [ ] Send a Media Message Template*
- [ ] Send an Image Message
- [ ] Send a Contact
- [ ] Send a Video Message
- [ ] Send a Link Button*
- [ ] Send a Location
- [ ] Send an Audio Message
- [ ] Send a Quick Reply Button*
- [ ] Send a File Message

* = unable to test these, due to the limitation of the Sandbox `verify` template

**Viber**
- [ ] Send an Image Message

2020-06-29 14:51 UTC, mheap commented
Should these samples be in the `node-code-snippets` repo?

2020-06-30 07:27 UTC, marklewin commented
> Should these samples be in the `node-code-snippets` repo?

I can't find any repo of that name? And Alex pushed his most recent changes here (https://github.com/Nexmo/nexmo-node-code-snippets/pull/86)

2020-06-30 12:38 UTC, mheap commented
🤦 We're in the `nexmo-node-code-snippets` repo already! Sorry, I misread this as the NDP repo before

2020-07-02 16:39 UTC, slorello89 requested changes
Couple minor items - working with @pardel to see if I can get an account to test out the more advanced stuff.

2020-07-02 16:39 UTC, slorello89 commented on .env-example
> +FB_RECIPIENT_ID=3881986391874929
Is this a real sender id?

2020-07-02 16:39 UTC, slorello89 commented on .env-example
> +BASE_URL=https://messages-sandbox.nexmo.com/
this only needs to be a hostname - it should not have the scheme - at least not in the context in which it's being used

2020-07-02 16:39 UTC, slorello89 commented on .env-example
> +MESSAGES_API_URL=https://messages-sandbox.nexmo.com/v0.1/messages
this field doesn't appear to be being used.

2020-07-03 09:03 UTC, marklewin commented on .env-example
> +MESSAGES_API_URL=https://messages-sandbox.nexmo.com/v0.1/messages
Removed!

2020-07-03 09:03 UTC, marklewin commented on .env-example
> +BASE_URL=https://messages-sandbox.nexmo.com/
Changed!

2020-07-03 09:03 UTC, marklewin commented on .env-example
> +FB_RECIPIENT_ID=3881986391874929
Good spot! 😊  Removed.

2020-07-06 09:21 UTC, marklewin commented
> Couple minor items - working with @pardel to see if I can get an account to test out the more advanced stuff.

Thanks @slorello89 . If you are referring to the WhatsApp template examples I think that might be quite hard to do - you would need to set up templates using either your own WhatsApp business account (hard to obtain AFAIK) or get access to the Sandbox templates (which I have found impossible). I've just based these on the `curl` examples we were given at some point, but have been unable to test them because the only Sandbox template available is the `verify` one, which I have documented [here](https://developer.nexmo.com/messages/concepts/messages-api-sandbox#whatsapp-templates-for-use-with-the-messages-api-sandbox).

2020-07-06 15:18 UTC, slorello89 approved these changes
I've tested all of the snippets in this review - looks good to me.

2020-07-06 15:32 UTC, merged